---
title: "Chapter 5 Part 2"
subtitle: "STAT 5700: Probability"
author: "Prof. Katie Fitzgerald, PhD"
institute: "Villanova University Department of Mathematics & Statistics"
date: "Fall 2025"
output: 
  pdf_document:
    includes:
      in_header: preamble.tex
    toc: true
editor_options: 
  markdown: 
    wrap: 72
---

```{r, echo = FALSE, message=FALSE, warning = FALSE}
library(tidyverse)
```

\pagebreak

# ADD 5.8

# ADD 5.9

# ADD 5.10

# 5.11 Conditional Expectation

Conditional distributions can be used to computed probabilities and
expected values just as with any distribution:

$$P\left(a<Y<b|X=x\right) = \sum_{y = a}^b h(y|x)$$
$$E\left[u(Y)|X = x\right] = \sum_y u(y)h(y|x)$$ For example, the
\textcolor{red}{\textbf{conditional mean}} and
\textcolor{red}{\textbf{conditional variance}} of $Y$ given $X = x$ is
defined as $$\mu_{Y|x} = E(Y|x)=\sum_y y h(y|x)$$
$$\sigma^2_{Y|x} = V(Y|x)=\sum_y (y - \mu_{Y|x})^2 h(y|x)$$ The
"shortcut" formula also applies:
$\sigma^2_{Y|x} = E[Y^2|x] - [E(Y|x)]^2$

[ADAPT FOR MEAN/VARIANCE ONLY]
::: {.activitybox data-latex=""}
**Example:**

Let $$f\left(x,y\right)=\frac{x+y}{21},\ \ \ \ x=1,2,3,\ \ \ \ y=1,2.$$
In 4.1 we found marginal pmf's:
$$f_x\left(x\right)=\frac{2x+3}{21},\ \ \ \ x=1,2,3,\ \ \ \ \text{and}\ \ \ f_y\left(y\right)=\frac{y+2}{7},\ \ \ \ y=1,2.$$

1.  Produce a table for the joint/marginal pmfs
2.  Find the conditional pmfs of $X$ given $Y = y$ and add a table for
    this
3.  Find the conditional mean and variance of $X$ when $Y = 2$.
4.  Find the conditional pmfs of $Y$ given $X = x$ and add a table for
    this
5.  Find the conditional mean and variance of $Y$ when $X = 2$.

\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
:::

[ADAPT FOR JUST MEAN/VARIANCE]

::: {.activitybox data-latex=""}
**Example:**

*From Hogg, Tanis, and Zimmerman: Exercise 4.3-9* <br/>\
Let $X$ and $Y$ have a uniform distribution on the set of points with
integer coordinates in
$S = \{(x, y) : 0 \leq x \leq 7, \ \ \ x \leq y \leq x+2\}$. That is,
$f(x,y) = 1/24, \ \ \ (x,y) \in S$, and both $x$ and $y$ are integers.
Find:

1.  $f_X(x)$ and $f_Y(y)$
2.  $h(y|x)$
3.  $E(Y|x)$
4.  $\sigma^2_{Y|x}$

\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
:::

\pagebreak

# UPDATE Chapter 5 Group Work

### Problem 1

Suppose that you randomly select a student from a large population of 4th grade students and record the student's sex and number of siblings. Let M = 1 if the selected student is male and M = 0 if the selected student is female. Let S record the student's number of siblings. The proportion of the population of students falling into each category of M and S is recorded in the table below.

| \# of siblings: | 0   | 1   | 2   | 3   | 4   |
|-----------------|-----|-----|-----|-----|-----|
| Female          | .10 | .18 | .12 | .07 | .04 |
| Male            | .12 | .18 | .14 | .03 | .02 |

a. What is the support of $M$? Of $S$?
b. Find the probability that the randomly selected student will be male with two siblings
c. Find $P(M = 0, S \leq 2)$
d. Find the probability that the randomly selected student will be an only child
e. Find the marginal distribution of $M$
f. Find the marginal distribution of $S$
g. Are $M$ and $S$ independent?

### Problem 2

Let the joint pmf of $X$ and $Y$ be $$f\left(x,y\right)=\frac{xy^2}{30},\ \ \ x=1,2,3,\ \ \ \ y=1,2$$

a.  What are the marginal distributions of $X$ and $Y$?
b.  Are X and Y independent?
c.  What is $P(X > 1)$?
d.  What is $E(X)$?

### Problem 3

Let $X$ and $Y$ be two continuous random variables with joint pdf $f(x,y) = \frac{3}{16}xy^2, \ \ \ \ 0 \leq x \leq 2, \ \ 0 \leq y \leq 2$. Are the two random variables independent?

### Problem 4

*[HTZ 4.4-2 - homework problem!]* Let $X$ and $Y$ have the joint pdf $f(x,y) = x + y, 0 \leq x \leq 1, 0 \leq y \leq 1$

a. Find the marginal pdfs $f_X(x)$ and $f_Y(y)$ and show that $X$ and $Y$ are dependent.
b. Compute:
    i. $\mu_X$
    ii. $\mu_Y$
    iii. $\sigma^2_X$
    iv. $\sigma^2_Y$

### Problem 5

Show that $Cov(X,Y) = E(XY) - \mu_X\mu_Y$. 

> *Hint: start with the definition $Cov(X,Y) = E[(X - \mu_X)(Y-\mu_Y)]$*

### Problem 6

Show that $E(XY) = \mu_X\mu_Y + \rho_{XY}\sigma_X\sigma_Y$ 

### Problem 7

Show that if two random variables $X$ and $Y$ are independent, then their covariance is 0. 

> *Hint: start with the shortcut formula $Cov(X,Y) = E(XY) - \mu_X\mu_Y$ and re-write $E(XY)$ as a double sum.*

### Problem 8

Return to the scenario in Problem 1. 

a. Find $E(M)$ and $V(M)$
a. Find $E(S)$ and $V(S)$
a. Find $Cov(M,S)$
a. Suppose that instead of just one student, you sample 12 students. Let $S_1, \dots S_{12}$ represent the number of siblings reported by each student (you can assume that these random variables are independent). Let $\overline{S} = \sum_{i = 1}^{12} \frac{S_i}{12}$ be the average number of siblings in the sample. Find $E(\overline{S})$ and $V(\overline{S})$