---
title: "Homework 01"
subtitle: "Sections 2.1 - 2.4"
author: "STAT 5700 - Probability"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Instructions

- Homework problems come from the 7th edition of the text *Mathematical Statistics with Applications* by Wackerly, Mendenhall, and Scheaffer, as well as (potential) additional problems provided by the instructor.
- You are responsible for understanding the concepts covered in all problems listed in a homework assignment, but only even-numbered problems should be turned in. 
- Be NEAT and show work to support your answers. Points will be deducted if your answer is not adequately supported or the work cannot be readily followed. 
- You are encouraged to work together on homework assignments, but each person must write up and turn in their own work and solutions. 
- You will turn in this assignment by scanning your work and uploading a single pdf to Blackboard. 
 

## Problems to do (responsible for content, but not collected/graded)

+ Section 2.3: 1, 5

+ Section 2.4: 11, 13, 15, 17, 19

+ Section 2.8: 91


## Problems to submit

+ Section 2.3: 2, 4, 6, 8

+ Section 2.4: 14, 18

+ Section 2.8: 86

+ Additional Problem #1 (required): Show that 

    a) $P(A_1 \cup A_2) \leq P(A_1) + P(A_2)$

    b) $P(A_1 \cap A_2) \geq P(A_1) + P(A_2) - 1$