---
title: "Homework 03"
subtitle: "Sections 2.10 - 3.1"
author: "STAT 5700 - Probability"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Instructions

- Homework problems come from the 7th edition of the text *Mathematical Statistics with Applications* by Wackerly, Mendenhall, and Scheaffer, as well as (potential) additional problems provided by the instructor.
- You are responsible for understanding the concepts covered in all problems listed in a homework assignment, but only even-numbered problems should be turned in. 
- Be NEAT and show work to support your answers. Points will be deducted if your answer is not adequately supported or the work cannot be readily followed. 
- You are encouraged to work together on homework assignments, but each person must write up and turn in their own work and solutions. 
- You will turn in this assignment by scanning your work and uploading a single pdf to Blackboard. 
- Note there is a corresponding R Lab (Lab 03) that will be due at the same time as this assignment (HW 03). 

## Problems to do (responsible for content, but not collected/graded)

+ Section 2.10: 125, 133, 137

+ Section 3.2: 1, 3, 5

## Problems to submit

+ Section 2.10: 124, 130, 132

+ Supplementary Exercises (end of chapter 2): 143, 156, 172

+ Section 3.2: 2, 6, 10


