---
title: "Homework 05"
subtitle: "Sections 3.4"
author: "STAT 5700 - Probability"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Instructions

- Homework problems come from the 7th edition of the text *Mathematical Statistics with Applications* by Wackerly, Mendenhall, and Scheaffer, as well as (potential) additional problems provided by the instructor.
- You are responsible for understanding the concepts covered in all problems listed in a homework assignment, but only even-numbered problems should be turned in. 
- Be NEAT and show work to support your answers. Points will be deducted if your answer is not adequately supported or the work cannot be readily followed. 
- You are encouraged to work together on homework assignments, but each person must write up and turn in their own work and solutions. 
- You will turn in this assignment by scanning your work and uploading a single pdf to Blackboard. 

**Feel free to use R for calculations involving the binomial distribution, but you should still show your work by writing out the formulas (e.g., $p(x)$) used to produce the probabilities**

## Problems to do (responsible for content, but not collected/graded)

+ Section 3.4: 37, 39, 51, 55, 59

## Problems to submit

+ Section 3.4: 38, 40, 44, 48, 50, 56, 58

