---
title: "Homework 04"
subtitle: "Sections 3.3 - 3.4"
author: "STAT 5700 - Probability"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Instructions

- Homework problems come from the 7th edition of the text *Mathematical Statistics with Applications* by Wackerly, Mendenhall, and Scheaffer, as well as (potential) additional problems provided by the instructor.
- You are responsible for understanding the concepts covered in all problems listed in a homework assignment, but only even-numbered problems should be turned in. 
- Be NEAT and show work to support your answers. Points will be deducted if your answer is not adequately supported or the work cannot be readily followed. 
- You are encouraged to work together on homework assignments, but each person must write up and turn in their own work and solutions. 
- You will turn in this assignment by scanning your work and uploading a single pdf to Blackboard. 
- Note there is a corresponding R Lab (Lab 04) that will be due at the same time as this assignment (HW 04). 

# NOTE:

*When working with the Binomial distribution, you can use the fact that if $Y \sim binom(n,p)$ then $E(Y) = np$ and $V(Y) = np(1-p)$. We will prove this later on.*

## Problems to do (responsible for content, but not collected/graded)

+ Section 3.3: 15, 21, 31

+ Section 3.4: 37, 39, 51, 55, 59

<!-- + Section 3.5: 67, 71, 73, 77 -->

## Problems to submit

+ Section 3.3: 12, 20, 22, 24, 30

+ Section 3.4: 44, 58

<!-- + Section 3.5: 70, 80 -->


