---
title: "Homework 10"
subtitle: "Sections 5.4 - 5.7"
author: "STAT 5700 - Probability"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Instructions

- Homework problems come from the 7th edition of the text *Mathematical Statistics with Applications* by Wackerly, Mendenhall, and Scheaffer, as well as (potential) additional problems provided by the instructor.
- You are responsible for understanding the concepts covered in all problems listed in a homework assignment, but only even-numbered problems should be turned in. 
- Be NEAT and show work to support your answers. Points will be deducted if your answer is not adequately supported or the work cannot be readily followed. 
- You are encouraged to work together on homework assignments, but each person must write up and turn in their own work and solutions. 
- You will turn in this assignment by scanning your work and uploading a single pdf to Blackboard. 
- Note there is a corresponding R Lab (Lab 10) that will be due at the same time as this assignment (HW 10). 

## Problems to do (responsible for content, but not collected/graded)

+ Section 5.4: 45, 49, 53, 63

+ Section 5.6: 77, 81, 87

+ Section 5.7: 89, 93, 95

## Problems to submit

+ Section 5.4: 48, 52, 60, 64

+ Section 5.6: 76, 80

+ Section 5.7: 92, 94

+ Additional Problems below:

1. Let X and Y be independent random variables with $\mu_X = 1$, $\sigma_X = 10$, $\mu_Y = 2$, and $\sigma_Y = 4$. Compute the mean and the standard deviation for:
  
    a. $X + Y$
    b. $X - Y$
    c. $X +4Y$
    d. $2X - 5Y$

2. Let X and Y be random variables such that $V (X) = 5$, $V (Y ) = 4$, and $Cov(X, Y ) = -2$. Find
    a. $Cov(X + Y, X-Y )$
    b. $Cov(X-Y, -2X + 5Y )$
    c. $Corr(X-Y, -2X + 5Y )$
    
3. The correlation between $X$ and $Y$ is given by $\rho_{XY}$. Assume that $\rho_{XY} \neq 0$. A linear transformation is performed on X, and this linearly transformed variable is called $W$, where $W = bX$ and $b$ is a positive constant. Show that $\rho_{WY} = \rho_{XY}$.



