---
title: "Exam 1 Review"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Chapter 2

1. How would you define probability, in words? 
\hfill\break
\hfill\break

1. What is a sample space, and what notation do we use for it?
\hfill\break
\hfill\break

1. What does $A \subset B$ mean, in words? Draw a picture of this relationship.
\hfill\break
\hfill\break
\hfill\break
\hfill\break

1. What does $A \cup B$ mean, in words? Draw a picture of this relationship.
\hfill\break
\hfill\break
\hfill\break
\hfill\break

1. What does $A \cap B$ mean, in words? Draw a picture of this relationship.
\hfill\break
\hfill\break
\hfill\break
\hfill\break

1. What does $A'$ mean, in words? Draw a picture of this event.
\hfill\break
\hfill\break
\hfill\break
\hfill\break

1. What notation do we use for the *null* or *empty* set?
\hfill\break
\hfill\break

1. What does **mutually exclusive** mean, in words? If $A$ and $B$ are mutually exclusive, what do we know about $A \cap B$? What about $A \cup B$?
\hfill\break
\hfill\break
\hfill\break
\hfill\break

1. What does **mutually exhaustive** mean, in words? If $A, B, C$ are mutually exhuastive, what do we know about $P(A \cup B \cup C)$?
\hfill\break
\hfill\break
\hfill\break

1. What is another way to re-write $A \cap (B \cup C)$?
\hfill\break
\hfill\break

1. What is another way to re-write $A \cup (B \cap C)$?
\hfill\break
\hfill\break

1. What is another way to re-write $(A \cup B)'$?
\hfill\break
\hfill\break

1. What is another way to re-write $(A \cap B)'$?
\hfill\break
\hfill\break

1. Probabilities always have to fall between what two values? \hfill\break
\hfill\break

1. If $A_1, A_2, A_3, ... A_k$ are disjoint events, how can you re-write $P(A_1 \cup A_2 \cup ... \cup A_k)$?
\hfill\break
\hfill\break

1. What is another way to re-write $1 - P(A')$?
\hfill\break
\hfill\break

1. What is $P(\emptyset)$?
\hfill\break
\hfill\break

1. TRUE/FALSE, If $A \subset B$, then $P(A) \leq P(B)$
\hfill\break
\hfill\break

1. If given $P(A \cup B)$, $P(A)$, and $P(B)$, how do you find $P(A \cap B)$?
\hfill\break
\hfill\break

1. If procedure 1 has $n_1$ possible outcomes, and procedure 2 has $n_2$ possible outcomes, how many possible outcomes does the composite procedure have?
\hfill\break
\hfill\break

1. What does $n!$ mean? 
\hfill\break
\hfill\break

1. What is the formula for the total number of ways to ORDER $r$ unique subjects selected from $n$ subjects (without replacement)? Is this a permutation or a combination? 
\hfill\break
\hfill\break

1. What is the formula for the total number of ways to order $r$ unique subjects selected WITH replacement from $n$ subjects?
\hfill\break
\hfill\break

1. What is the formula for the total number of ways to CHOOSE $r$ unique subjects selected from $n$ subjects (without replacement)? Is this a permutation or a combination? 
\hfill\break
\hfill\break

1. What is the formula for $n \choose r$? How do you read $n \choose r$, in words?
\hfill\break
\hfill\break

1. What is the formula for splitting $n$ distinct objects into $k$ distinct groups of size $n_1, n_2, \dots n_k$?
\hfill\break
\hfill\break

1. What's the formula for $P(B|A)$? What is this called?
\hfill\break
\hfill\break

1. If $A$ and $B$ are independent, what is $P(A|B)$? $P(B|A)$? $P(A\cap B)$?
\hfill\break
\hfill\break
\hfill\break

1. How can you re-write $P(A \cap B)$ in terms of a conditional probability? 
\hfill\break
\hfill\break

1. How do you check if two events $A$ and $B$ are independent? 
\hfill\break
\hfill\break

1. If A and B are independent, what do you know about A and B', A' and B, and A' and B'? 
\hfill\break
\hfill\break

1. Set up a tree diagram where the first experiment has two possible outcomes $A$ and $A'$, and the second experiment has two possible outcomes $B$ and $B'$. Label the each of the following on the appropriate branches or indicate if the probability is not represented by a branch: 
    + $P(A)$
    + $P(A')$
    + $P(A |B)$
    + $P(A'|B)$
    + $P(B|A)$
    + $P(B|A')$
    + $P(B'|A)$
    + $P(B'|A')$
\hfill\break
\hfill\break

1. Describe how you would use the tree diagram above to find:
    + $P(A \cap B)$
    + $P(A' \cap B')$
    + $P(B)$
    + $P(A | B)$


1. How can you re-write $P(A)$ using the Law of Total Probability? Explain in words what this means. How does it relate to Bayes Theorem?
\hfill\break
\hfill\break
\hfill\break
\hfill\break
\hfill\break
\hfill\break

### Chapter 3

1. What condition do you check to verify that a function $p(y)$ is a valid probability distribution?
\hfill\break
\hfill\break

1. What is $p(y)$ when $y \notin S$?
\hfill\break
\hfill\break

1. How do we write $p(y)$ in terms of a probability?
\hfill\break
\hfill\break

1. How do you find an expression for the mean of a discrete random variable? What are two ways to denote the mean?
\hfill\break
\hfill\break

1. How do you find $E[g(Y)]$ for a discrete random variable $Y$?
\hfill\break
\hfill\break

1. How can you simplify $E(aY + b)$?
\hfill\break
\hfill\break

1. How do you find the variance of a discrete random variable? (Shortcut formula)
\hfill\break
\hfill\break

<!-- 1. How do you find an expression for the moment-generating function of a discrete random variable? -->
<!-- \hfill\break -->
<!-- \hfill\break -->

<!-- 1. How do you find an expression for the $r^{th}$ moment of a discrete random variable? -->
<!-- \hfill\break -->
<!-- \hfill\break -->

<!-- 1. How do you use the mgf to find the mean of a random variable? That is, write $E(X)$ in terms of $M_X(t)$ -->
<!-- \hfill\break -->
<!-- \hfill\break -->

<!-- 1. How do you use the mgf to find the variance of a random variable? That is, write $V(X)$ in terms of $M_X(t)$ -->
<!-- \hfill\break -->
<!-- \hfill\break -->

<!-- 1. What is $E(X - \mu)$?  -->
<!-- \hfill\break -->
<!-- \hfill\break -->

1. What happens to the variance of $Y$ if a constant is added to all $y$ values? That is, what is $V(Y + c)$?
\hfill\break
\hfill\break

1. What happens to the variance is all $y$ values are multiplied by a constant? That is, what is $V(cY)$?
\hfill\break
\hfill\break

1. What is $V(aY + b)$?
\hfill\break
\hfill\break

\pagebreak

4. For each of the following distributions, list the mean, variance, and probability distribution. Note what scenarios each distribution is good for modeling.
    a. Uniform (discrete)
    a. Bernoulli
    a. Binomial


\pagebreak
