---
title: "Final Exam Review"
output: pdf_document
---

The final exam is CUMULATIVE, meaning it covers Chapters 2 - 5. The following packet reviews all the key concepts/definitions and is a good **starting place for creating your cheat sheet**. However, **to fully prepare for the exam you should do LOTS of practice problems** (See HW, group work, quizzes, extra textbook problems, etc. You can even ask ChatGPT to generate more problems for you!). 


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Chapter 2

1. What is a sample space, and what notation do we use for it?
\hfill\break
\hfill\break

1. What does $A \subset B$ mean, in words? Draw a picture of this relationship.
\hfill\break
\hfill\break
\hfill\break
\hfill\break

1. What does $A \cup B$ mean, in words? Draw a picture of this relationship.
\hfill\break
\hfill\break
\hfill\break
\hfill\break

1. What does $A \cap B$ mean, in words? Draw a picture of this relationship.
\hfill\break
\hfill\break
\hfill\break
\hfill\break

1. What does $A'$ mean, in words? Draw a picture of this event.
\hfill\break
\hfill\break
\hfill\break
\hfill\break

1. What notation do we use for the *null* or *empty* set?
\hfill\break
\hfill\break

1. What does **mutually exclusive** mean, in words? If $A$ and $B$ are mutually exclusive, what do we know about $A \cap B$? What about $A \cup B$?
\hfill\break
\hfill\break
\hfill\break
\hfill\break

1. What does **mutually exhaustive** mean, in words? If $A, B, C$ are mutually exhuastive, what do we know about $P(A \cup B \cup C)$?
\hfill\break
\hfill\break
\hfill\break

1. What is another way to re-write $A \cap (B \cup C)$?
\hfill\break
\hfill\break

1. What is another way to re-write $A \cup (B \cap C)$?
\hfill\break
\hfill\break

1. What is another way to re-write $(A \cup B)'$?
\hfill\break
\hfill\break

1. What is another way to re-write $(A \cap B)'$?
\hfill\break
\hfill\break

1. Probabilities always have to fall between what two values? \hfill\break
\hfill\break

1. If $A_1, A_2, A_3, ... A_k$ are disjoint events, how can you re-write $P(A_1 \cup A_2 \cup ... \cup A_k)$?
\hfill\break
\hfill\break

1. What is another way to re-write $1 - P(A')$?
\hfill\break
\hfill\break

1. What is $P(\emptyset)$?
\hfill\break
\hfill\break

1. TRUE/FALSE, If $A \subset B$, then $P(A) \leq P(B)$
\hfill\break
\hfill\break

1. If given $P(A \cup B)$, $P(A)$, and $P(B)$, how do you find $P(A \cap B)$?
\hfill\break
\hfill\break

1. If procedure 1 has $n_1$ possible outcomes, and procedure 2 has $n_2$ possible outcomes, how many possible outcomes does the composite procedure have?
\hfill\break
\hfill\break

1. What does $n!$ mean? 
\hfill\break
\hfill\break

1. What is the formula for the total number of ways to ORDER $r$ unique subjects selected from $n$ subjects (without replacement)? Is this a permutation or a combination? 
\hfill\break
\hfill\break

1. What is the formula for the total number of ways to order $r$ unique subjects selected WITH replacement from $n$ subjects?
\hfill\break
\hfill\break

1. What is the formula for the total number of ways to CHOOSE $r$ unique subjects selected from $n$ subjects (without replacement)? Is this a permutation or a combination? 
\hfill\break
\hfill\break

1. What is the formula for $n \choose r$? How do you read $n \choose r$, in words?
\hfill\break
\hfill\break

1. What is the formula for splitting $n$ distinct objects into $k$ distinct groups of size $n_1, n_2, \dots n_k$?
\hfill\break
\hfill\break

1. What's the formula for $P(B|A)$? What is this called?
\hfill\break
\hfill\break

1. If $A$ and $B$ are independent, what is $P(A|B)$? $P(B|A)$? $P(A\cap B)$?
\hfill\break
\hfill\break
\hfill\break

1. How can you re-write $P(A \cap B)$ in terms of a conditional probability? 
\hfill\break
\hfill\break

1. How do you check if two events $A$ and $B$ are independent? 
\hfill\break
\hfill\break

1. If A and B are independent, what do you know about A and B', A' and B, and A' and B'? 
\hfill\break
\hfill\break

1. Set up a tree diagram where the first experiment has two possible outcomes $A$ and $A'$, and the second experiment has two possible outcomes $B$ and $B'$. Label the each of the following on the appropriate branches or indicate if the probability is not represented by a branch: 
    + $P(A)$
    + $P(A')$
    + $P(A |B)$
    + $P(A'|B)$
    + $P(B|A)$
    + $P(B|A')$
    + $P(B'|A)$
    + $P(B'|A')$
\hfill\break
\hfill\break

1. Know how you would use the tree diagram above to find: $P(A \cap B)$, $P(A' \cap B')$, $P(B)$, $P(A | B)$
\hfill\break
\hfill\break

1. How can you re-write $P(A)$ using the Law of Total Probability? Explain in words what this means. How does it relate to Bayes Theorem?
\hfill\break
\hfill\break
\hfill\break
\hfill\break
\hfill\break
\hfill\break

### Chapters 3 & 4

34. For each of the following distributions, list the mean, variance, pdf/pmf, mgf (if it exists), and support. Note what scenarios each distribution is good for modeling and any connections it has to other distributions.
    a. Uniform (discrete)
    a. Bernoulli
    a. Binomial
    a. Geometric
    a. Hypergeometric
    a. Poisson
    a. Negative Binomial
    a. Uniform (continuous)
    a. Normal
    a. Exponential
    a. Gamma
    a. Chi-square
    a. Beta
    a. Multinomial (also know $Cov(Y_s, Y_t)$ for this distribution)

\pagebreak

35. What condition do you check to verify that a function $p(y)$ is a valid probability distribution? What about $f(y)$?
\hfill\break
\hfill\break

1. What is $p(y)$ when $y \notin S$?
\hfill\break
\hfill\break

1. How do we write $p(y)$ in terms of a probability?
\hfill\break
\hfill\break

1. How do you find an expression for the mean of a discrete random variable? A continuous random variable? What are two ways to denote the mean?
\hfill\break
\hfill\break

1. How do you find an expression for the variance of a discrete random variable? A continuous random variable? What are two ways to denote the variance?
\
\
\

1. What is the shortcut formula for the variance?
\
\
\

1. How do you find $E[g(Y)]$ for a discrete random variable $Y$? For a continuous random variable?
\hfill\break
\hfill\break

1. How can you simplify $E(aY + b)$?
\hfill\break
\hfill\break


1. How do you find an expression for the moment-generating function of a continuous random variable? A discrete random variable?
\
\
\

1. How do you find an expression for the $r^{th}$ moment of a continuous random variable? A discrete random variable?
\
\
\
1. How do you use the mgf to find the mean of a random variable? That is, write $E(Y)$ in terms of $m(t)$
\
\
\
1. How do you use the mgf to find the variance of a random variable? That is, write $V(Y)$ in terms of $m(t)$
\
\
\

1. What happens to the variance of $Y$ if a constant is added to all $y$ values? That is, what is $V(Y + c)$?
\hfill\break
\hfill\break

1. What happens to the variance is all $y$ values are multiplied by a constant? That is, what is $V(cY)$?
\hfill\break
\hfill\break

1. What is $V(aY + b)$?
\hfill\break
\hfill\break

45. How can $e^x$ (or $e^{\lambda}$ be written as an infinite series? Remind yourself how this is relevant to the Poisson distribution.
\
\
\
\

1. What's the relationship between the pdf and the cdf? That is, if you're given the pdf, how do you find the cdf? If you're given the cdf, how do you find the pdf? 
\
\
\
\
\
1. Write $P(a < Y < b)$ as an integral. How do you find this value using the cdf? 
\
\
\
\
1. Write $P(Y \leq y)$ as an integral. What do we call this function? 
\
\
\

1. How do you find the standard deviation of a random variable if given its pdf? 
\
\
\
\
\
1. When $X ~ N(\mu, \sigma^2)$ and $Z = \frac{X - \mu}{\sigma}$:
    a. what is $E(Z)$ and $V(Z)$? 
    \
\
    a. How is $Z$ distributed?
    \
\
    a. How is $Z^2$ distributed?
    \
\
\pagebreak 

# Chapter 5

56. What condition do you have to check to verify $p(x,y)$ is a valid joint pmf for 2 discrete random variables? 
\
\
\
\
1. What condition do you have to check to verify $f(x,y)$ is a valid pdf for 2 continuous random variables? 
\
\
\
\
1. If given the joint pmf/pdf, how do you find the marginal distribution of $X$? Of $Y$?
\
\
\
\
\
\

1. What is an expression for $p(x|y)$, for discrete random variables?  What intermediate step do you have to do to find $p(x|y)$ if you are given $p(x,y)$? Make sure you know the analogous steps for continuous distribution $f(x|y)$.
\
\
\
\
1. What is an expression for $p(y|x)$, for discrete random variables? What intermediate step do you have to do to find $p(y|x)$ if you are given $p(x,y)$? Make sure you know the analogous steps for continuous distribution $f(y|x)$.
\
\
\
\
1. Write an expression for $E(Y|X)$
\
\
1. Write an expression for $V(Y|X)$ using the shortcut formula
\
\

1. When $X$ and $Y$ are independent, what implications does that have on:
    a. $E(XY)$
    b. $f(x,y)$
    c. $Cov(X,Y)$
    d. $\rho_{XY}$
    e. $V(X + Y)$

1. What is an expression for $V(X + Y)$ when $X$ and $Y$ are not independent?
\
\
\
\
1. What condition do you check to determine whether $X$ and $Y$ are independent?
\
\
1. Write $F(y_1, y_2)$ as a probability, then as a double sum (or double integral)
\
\
\
\
\
1. What's an expression for $E(g(X,Y))$ when $X$ and $Y$ are continuous random variables? When they are discrete?
\
\
\
\

1. What is the relationship between correlation and covariance?
\
\
\
\
1. What is the definition for covariance, written in terms of expected value?
\
\
\
\
1. What is the shortcut formula for covariance?
\
\
\
\
1. How would you find $E(XY)$ if given the means, variances, and correlation of $X$ and $Y$?
\
\
\
\
1. What's the relationship between correlation and the slope of the line of best fit? 
\
\
\
\
1. What is $Cov(X,X)$?
\
\
\
\
1. If $W = \sum_{i = 1}^n a_iX_i$, what is an expression for $E(W)$? For $V(W)$? 
\
\
\
\

1. What is an expression for $Cov(\sum_{i = 1}^n a_iX_i, \sum_{j = 1}^m b_iY_i$)?
\
\
\
\
1. What is the expected value and variance of the sample mean? 
\
\
\
\
1. What is an expression for the conditional mean of a function g(X), given $Y = y$ for a discrete random variable $X$? For a continuous random variable?
\
\
\
\
1. How can you write $E(X)$ in terms of conditional expectations?
\
\
\
\
1. How can you write $V(X)$ in terms of conditional expectations?
<!-- 1. In R, how do you find the probability of $P(a < X < b)$ -->
<!--     a. for the normal distribution? What parameters do you have to specify? -->
<!--     \ -->
<!-- \ -->
<!-- \ -->
<!-- \ -->
<!--     a. for the chi-square distribution? What parameters do you have to specify? -->
<!--     \ -->
<!-- \ -->
<!-- \ -->
<!-- \ -->
<!--     a. for the gamma distribution? What parameters do you have to specify? -->
<!--     \ -->
<!-- \ -->
<!-- \ -->
<!-- \ -->
<!--     a. for the uniform distribution? What parameters do you have to specify? -->
<!--     \ -->
<!-- \ -->
<!-- \ -->
<!-- \ -->
<!--     a. for the exponential distribution? What parameters do you have to specify? -->
<!--     \ -->
<!-- \ -->
<!-- \ -->
<!-- \ -->
<!--     a. for the beta distribution? What parameters do you have to specify? -->
<!--     \ -->
<!-- \ -->
<!-- \ -->
<!-- \ -->

<!-- 1. In R, how do you find the value of $x$ such that $P(X \leq x) = p$ -->
<!--     a. for the normal distribution? -->
<!--     \ -->
<!-- \ -->
<!-- \ -->
<!-- \ -->
<!--     a. for the chi-square distribution? -->
<!--     \ -->
<!-- \ -->
<!-- \ -->
<!-- \ -->
<!--     a. for the gamma distribution? -->
<!--     \ -->
<!-- \ -->
<!-- \ -->
<!-- \ -->
<!--     a. for the uniform distribution? -->
<!--     \ -->
<!-- \ -->
<!-- \ -->
<!-- \ -->
<!--     a. for the exponential distribution? -->
<!--     \ -->
<!-- \ -->
<!-- \ -->
<!-- \ -->
<!--     a. for the beta distribution? -->
<!--     \ -->
<!-- \ -->
<!-- \ -->
<!-- \ -->
<!-- 1. In R, how do you find the probability of $P(X > a)$ for the normal distribution? -->
<!-- \ -->
<!-- \ -->
<!-- \ -->
<!-- \ -->
<!-- 1. In R, how do you find the value of $x$ such that $P(X \geq x) = p$ for the normal distribution? -->

\pagebreak

Know what each of the following symbols/expressions represent

+ $\mu$
\
+ $\sigma^2$
\
+ $\sigma$
\
+ $\Gamma(\alpha)$
\
+ $Beta(\alpha, \beta)$
\
+ $F(y)$
\
+ $f(y)$
\
+ $E(Y)$
\
+ $V(Y)$
\
+ $m(t)$
\
+ $p(x,y)$
\
+ $f(x,y)$
\
+ $F(x,y)$
\
+ $p_X(x)$, $p_Y(y)$
\
+ $f_X(x)$, $f_Y(y)$
\
+ $p(x|y)$, $p(y|x)$
\
+ $f(x|y)$, $f(y|x)$
\
+ $\sigma_{XY}$
\
+ $\rho_{XY}$
