---
title: "HW 07 SOLUTIONS"
format: pdf
---

# Practice Problems

## 4.5  
For $y = 2, 3, \dots$  
$F(y) - F(y-1) = P(Y \le y) - P(Y \le y-1) = P(Y = y) = p(y)$  
Also, $F(1) = P(Y \le 1) = P(Y = 1) = p(1)$

## 4.9  
(a) $Y$ is discrete since $F(y)$ is not continuous. Also the set of possible values of $Y$ represents a countable set.  
(b) Possible values: $2, 2.5, 4, 5.5, 6, 7$  
(c)  
$p(2)=\tfrac{1}{8}$,  
$p(2.5)=\tfrac{3}{16}-\tfrac{1}{8}=\tfrac{1}{16}$,  
$p(4)=\tfrac{1}{2}-\tfrac{3}{16}=\tfrac{5}{16}$,  
$p(5.5)=\tfrac{5}{8}-\tfrac{1}{2}=\tfrac{1}{8}$,  
$p(6)=\tfrac{11}{16}-\tfrac{5}{8}=\tfrac{1}{16}$,  
$p(7)=1-\tfrac{11}{16}=\tfrac{5}{16}$  
(d) $P(Y \le \phi_{0.5})=F(\phi_{0.5})=0.5 \Rightarrow \phi_{0.5}=4$

## 4.11  
(a) $1 = \int_0^2 c y\,dy = [cy^2/2\Big|_0^2=2c \Rightarrow c = \tfrac{1}{2}$  
(b) $F(y) = \int_0^y \tfrac{1}{2}t\,dt = \tfrac{1}{4}y^2,\ 0 \le y \le 2$  
(d) $P(1 \le Y \le 2) = F(2) - F(1) = 1 - 0.25 = 0.75$

## 4.17  
(a) $1 = \int_0^1 (c y^2 + y)\,dy = [cy^3/3 + y^2/2\Big|_0^2 \Rightarrow c = \tfrac{3}{2}$  
(b) $F(y) = \tfrac{1}{2}y^3 + y^2/2,\ 0 \le y \le 1$  
(d) $F(-1)=0,\ F(0)=0,\ F(1)=1$  
(e) $P(Y < 0.5)=F(0.5)=\tfrac{3}{16}$  
(f) $P(Y \ge 0.5 \mid Y \ge 0.25)=\dfrac{P(Y \ge 0.5)}{P(Y \ge 0.25)}=\dfrac{1 - F(0.5)}{1 - F(0.25)} = 0.8455285$

## 4.19  
(a)  
$$
f(y) =
\begin{cases}
0, & y \le 0 \\
0.125, & 0<y<2 \\
0.125y, & 2 \le y < 4 \\
0, & y \ge 4
\end{cases}
$$  
(b) $F(3) - F(1) = \tfrac{7}{16}$  
(c) $1 - F(1.5) = \tfrac{13}{16}$  
(d) $\dfrac{7/16}{9/16} = \tfrac{7}{9}$

## 4.21  
$E(Y) = \tfrac{17}{24} \approx 0.708$  
$E(Y^2) = 0.55$  
$V(Y) = 0.55 - (0.708)^2 = 0.0487$

## 4.33  
(a) $E(Y) = 5.5,\ V(Y) = 0.15$  
(b) Two-SD interval: $5.5 \pm 2\sqrt{0.15} \approx (4.725, 6.275)$  
Since $Y \ge 5$, interval is $(5, 6.275)$  
(c) $P(Y < 5.5) \approx 0.58$

## 4.39  
The distance $Y$ is uniformly distributed on the interval A to B, If she is closer to A, she
has landed in the interval $(A, \frac{A + B}{2})$. This is one half the total interval length, so the
probability is .5. If her distance to A is more than three times her distance to B, she has
landed in the interval $(\frac{3B + A}{4}, B)$. This is one quarter the total interval length, so the
probability is .25.

## 4.43  
$E(A) = \pi E(R^2) = \pi\int_0^1r^2dr=\tfrac{\pi}{3}$  
$V(A) = \pi^2V(R^2) =\pi^2 [E(R^4) - (E(R^2))^2] = \pi^2 \left(\int_0^1r^4dr - (\frac{1}{3})^2\right) = \pi^2 \left(\tfrac{1}{5} - \tfrac{1}{9}\right) = \tfrac{4\pi^2}{45}$

## 4.53  
Let Y = time when the defective circuit board was produced. Then, Y has an approximate
uniform distribution on the interval (0, 8). That is, $Y \sim \text{Uniform}(0,8)$  
(a) $P(0<Y<1)=\tfrac{1}{8}$,  
(b) $P(7<Y<8)=\tfrac{1}{8}$,  
(c) $P(4<Y<5 \mid Y>4)=\dfrac{1/8}{1/2}=\tfrac{1}{4}$

## 4.59  
(a) $z_0=0$  
(b) $z_0=1.10$  
(c) $z_0=1.645$  
(d) $z_0=2.576$

## 4.73  
$Y \sim N(950, 10^2)$  

(a) $P(947 \le Y \le 958) = P(-0.3 \le Z \le 0.8) = 0.406$  

(b) $P(Y \le c) = 0.8531 \Rightarrow z_0 = 1.05$  
$c = 950 + (1.05)(10) = 960.5\ \text{mm}$


# Submitted Problems

## 4.2  
(a) $p(1)=0.2$, $p(2)=(1/4)(4/5)=0.2$, $p(3)=(1/3)(3/4)(4/5)=0.2$, $p(4)=0.2$, $p(5)=0.2$  
(b) 
$F(y) = P(Y \le y) = 
\begin{cases} 
0.2, & 1 \le y < 2 \\ 
0.4, & 2 \le y < 3 \\ 
0.6, & 3 \le y < 4 \\ 
0.8, & 4 \le y < 5 \\ 
1, & y \ge 5 
\end{cases}$  
(c) $P(Y < 3)=F(2)=0.4$, $P(Y \le 3)=0.6$, $P(Y=3)=p(3)=0.2$  
(d) No, $Y$ is discrete

## 4.8  
(a) $k=6$ to normalize the density  
(b) $P(0.4 \le Y \le 1)=0.648$  
(c) same as (b)  
(d) $P(Y \le 0.4 \mid Y \le 0.8)=0.352/0.896=0.393$  
(e) same as (d)

## 4.18  
(a) $\int_0^2 0.2\,dy + \int_2^1 (.2 + cy)dy = 0.4 + c/2 = 1 \Rightarrow c=1.2$  
(b) 
$F(y) = 
\begin{cases}
0, & y \le -1 \\ 
0.2(1 + y), & -1<y\le0 \\ 
0.2(1 + y + 3y^2), & 0<y\le1 \\ 
1, & y>1
\end{cases}$  
(c) Not shown
(d) $F(-1)=0$, $F(0)=0.2$, $F(1)=1$  
(e) $P(Y>0.5 \mid Y>0.1)=0.55/0.774 \approx 0.71$

## 4.22  
$E(Y)=\int y f(y) dy = 0.4$  
$V(Y)=\int y^2 f(y) dy - (0.4)^2 = 0.2733$

## 4.30  
(a) $E(Y)=2/3$, $V(Y)=1/2-(2/3)^2=1/18$  
(b) $X=200Y-60$, $E(X)=200(2/3)-60=220/3$, $V(X)=20000/9$  
(c) Using Tchebysheff's theorem, a two-SD interval about the mean is given by: $220/3 \pm 2\sqrt{20000/9} \approx (-20.948, 167.614)$

## 4.40  
$X=$ # parachutists past midpoint, $X \sim Binomial(n=3,p=1/2)$  
$P(X=1)=3(1/2)^3=0.375$

## 4.42  
$F(y)=(y-\theta_1)/(\theta_2-\theta_1)$ for $\theta_1 \le y \le \theta_2$. For $F(\phi_{0.5}) = 0.5$, then  
$\phi_{0.5} = \theta_1 + 0.5(\theta_2-\theta_1)=0.5(\theta_1+\theta_2)$. This is also the mean of the distribution.

## 4.48  
Let $Y$ be the location of the selected point. Then, $Y \sim Uniform(0,500)$  
(a) $P(475\le Y\le500)=1/20$  
(b) $P(0\le Y\le25)=1/20$  
(c) $P(0<Y<250)=1/2$

## 4.62  
(a) $P(Z^2<1)=P(-1<Z<1)=0.6826$  
(b) $P(Z^2<3.84146)=P(-1.96<Z<1.96)=0.95$

## 4.80  
$A=L*W=|Y|*3|Y|=3Y^2$  
$E(A)=3E(Y^2)=3(\sigma^2+\mu^2)$




