---
title: "HW 03 SOLUTIONS"
format: pdf
---

# Practice Problems

## 2.71

a. $P(A|B) = \frac{0.1}{0.3} = \frac{1}{3}.$
b. $P(B|A) = \frac{0.1}{0.5} = \frac{1}{5}.$
c. $P(A|A \cup B) = \frac{0.5}{0.5 + 0.3 - 0.1} = \frac{5}{7}.$
d. $P(A|A \cap B) = 1,$ since A has occurred.
e. $P(A \cap B|B) = \frac{0.1}{0.5 + 0.3 - 0.1} = \frac{1}{7}.$

## 2.75

a. Given the first two cards drawn are spades, there are 11 spades left in the deck. The probability is $\frac{\binom{11}{3}}{\binom{50}{3}} = 0.0084.$ Note: this is also equal to $P(S_3S_4S_5|S_1S_2)$.

b. Given the first three cards drawn are spades, there are 10 spades left. The probability is $\frac{\binom{10}{2}}{\binom{49}{2}} = 0.0383.$ Note: this is also equal to $P(S_4S_5|S_1S_2S_3)$.

c. Given the first four cards drawn are spades, there are 9 spades left. The probability is
$\frac{\binom{9}{1}}{\binom{48}{1}} = 0.1875.$ Note: this is also equal to $P(S_5|S_1S_2S_3S_4)$.

## 2.79

If A and B are mutually exclusive, $P(A \cap B) = 0$. But, $P(A) P(B) > 0$. So they are not independent.

## 2.85

$P(A \mid \overline{B}) = P(A \cap \overline{B}) / P(\overline{B})
= \dfrac{P(\overline{B} \mid A) P(A)}{P(\overline{B})}
= \dfrac{[1 - P(B \mid A)] P(A)}{P(\overline{B})}
= \dfrac{[1 - P(B)] P(A)}{P(\overline{B})}
= \dfrac{P(\overline{B}) P(A)}{P(\overline{B})}
= P(A).$ So, $A$ and $\overline{B}$ are independent.

$P(\overline{B} \mid \overline{A}) = P(\overline{B} \cap \overline{A}) / P(\overline{A})
= \dfrac{P(\overline{A} \mid \overline{B}) P(\overline{B})}{P(\overline{A})}
= \dfrac{[1 - P(A \mid \overline{B})] P(\overline{B})}{P(\overline{A})}.$  From the above, $A$ and $\overline{B}$ are independent.  So $P(\overline{B} \mid \overline{A})
= \dfrac{[1 - P(A)] P(\overline{B})}{P(\overline{A})}
= \dfrac{P(\overline{A}) P(\overline{B})}{P(\overline{A})}
= P(\overline{B}).$ So, $\overline{A}$ and $\overline{B}$ are independent.

## 2.125

Define the events: $D$: has the disease, $H$: test indicates the disease. Thus, $P(H|D) = 0.9$,  and $P(H'|D') = 0.9$, $P(D) = 0.01$, $P(D') = 0.99$. Then by Bayes’ rule, $P(D|H) = \frac{P(H|D)P(D)}{P(H|D)P(D) + P(H|D')P(D')} = \frac{0.9(0.01)}{0.9(0.01) + 0.01(0.99)} = \tfrac{1}{12}$.

## 2.133

Define the events: $G$: student guesses, $C$: student is correct. Then $P(G'|C) = \frac{P(C|G')P(G')}{P(C|G')P(G') + P(C|G)P(G)}= 0.9412$.

## 2.137

Let $A = \{\text{both balls are white}\}$ and for $i = 1,2,\dots,5$, let $A_i =$ “both balls selected from bowl $i$ are white.” Then $\bigcup A_i = A$. Also let $B_i =$ “bowl $i$ is selected.” Then $P(B_i) = 0.2$ for all $i$.  
a. $P(A) = \sum_{i=1}^5 P(A|B_i)P(B_i) = \frac{1}{5}[0 + \frac{2}{5}\frac{1}{4} + \frac{3}{5}\frac{2}{4} + \frac{4}{5} \frac{3}{4} + 1] = 2/5$  
b. By Bayes’ rule, $P(B_3|A) = (3/50)/(2/50) = 3/20$.


# Submitted Problems

## 2.72

Note that $P(A) = 0.6$ and $P(A \mid M) = \frac{0.24}{0.4} = 0.6$. So, $A$ and $M$ are independent. Similarly, $P(A' \mid F) = \frac{0.24}{0.6} = 0.4 = P(A'),$ so $A'$ and $F$ are independent.

## 2.74

a. $P(A) = 0.61$, $P(D) = 0.30$, $P(A \cap D) = 0.20$. Dependent.

b. $P(B) = 0.30$, $P(D) = 0.30$, $P(B \cap D) = 0.09$. Independent.

c. $P(C) = 0.09$, $P(D) = 0.30$, $P(C \cap D) = 0.01$. Dependent.



## 2.80

If $B \subset A$, then $P(A \cap B) = P(A) \neq P(A)P(B),$ unless $B = S$ (in which case $P(B) = 1$).



## 2.90

a. $(1/50)(1/50) = 0.0004$

b. $P(\text{at least one injury})
= 1 - P(\text{no injuries in 50 jumps})
= 1 - \left(\frac{49}{50}\right)^{50} \approx 0.636$. Your friend is not correct.



## 2.94

Define the events $A$: device A detects smoke, $B$: device B detects smoke.

a. $P(A \cup B) = P(A) + P(B) - P(A \cap B) = 0.95 + 0.90 - 0.88 = 0.97$

b. $P(\text{smoke undetected}) = 1 - P(A \cup B) = 1 - 0.97 = 0.03$

## 2.110

Define the events:

- $I$: item is from line I
- $II$: item is from line II
- $N$: item is not defective

Then, $P(N) = P(N \cap (I \cup II)) = P(N \cap I) + P(N \cap II) = 0.92(0.4) + 0.90(0.6) = 0.908$


## 2.124

Define the events: $D$: democrat, $R$: republican, $F$: favors issue. Then $P(D|F) = \frac{P(F|D)P(D)}{P(F|D)P(D) + P(F|R)P(R)} = \frac{(0.7)(0.6)}{(0.7)(0.6) + (0.3)(0.4)} = 7/9$.

## 2.130

Define the events: $C$: contract lung cancer, $S$: worked in a shipyard. Given $P(S|C) = 0.22$, $P(S|C') = 0.14$, and $P(C) = 0.0004$. By Bayes’ rule, $P(C|S) = \frac{P(S|C)P(C)}{P(S|C)P(C) + P(S|C')P(C')} = \frac{(0.22)(0.0004)}{(0.22)(0.0004) + (0.14)(0.9996)} \approx 0.0006$.

## 2.132

For $i=1,2,3$, let $F_i =$ plane is found in region $i$, $N_i =$ not found in region $i$, $R_i =$ plane is in region $i$. Then $P(F_i|R_i) = 1-\alpha_i$ and $P(R_i)=1/3$.  
a. $P(R_1|N_1) = \frac{P(N_1|R_1)P(R_1)}{P(N_1|R_1)P(R_1) + P(N_1|R_2)P(R_2) + P(N_1|R_3)P(R_3)} = \frac{\alpha_1(1/3)}{\alpha_1(1/3) + (1/3) + (1/3)} = \frac{\alpha_1}{\alpha_1+2}$.  
b. $P(R_2|N_1) = \frac{1/3}{\alpha_1/3 + 1/3 + 1/3} = \frac{1}{\alpha_1+2}$.  
c. $P(R_3|N_1) = \frac{1}{\alpha_1+2}$.

## 2.143

Since $P(B) = P(B \cap A) + P(B \cap A')$, dividing each part by $P(B)$ gives $1 = \frac{P(B \cap A)}{P(B)} + \frac{P(B \cap A')}{P(B)} = P(A|B) + P(A'|B)$

## 2.156

a. i. $1 - 5686/97900 = 0.942$.
   ii. $(97900-43354)/97900 = 0.557$.
   iii. $10560/14113 = 0.748$. 
   iv. $(646+375+568)/11533 = 0.138$.  
b. If the US population in 2002 was known, this could be used to divide into the total number of deaths in 2002 to give a probability.

## 2.172

Only $P(A|B) + P(A'|B) = 1$ is true for any events $A$ and $B$.

