---
title: "HW 05 SOLUTIONS"
format: pdf
---

# Practice Problems

## 3.37

a. Not a binomial random variable.
b. Not a binomial random variable.
c. Binomial with n = 100, p = proportion of high school students who scored above 1026.
d. Not a binomial random variable (not discrete).
e. Not binomial, since the sample was not selected among all female HS grads.

## 3.39

Let Y = # of components failing in less than 1000 hours. Then, Y is binomial with n = 4 and p = .2.

a. $P(Y = 2) = {{4}\choose{2}}0.2^2).8^2 = 0.1536$
b. The system will operate if 0, 1, or 2 components fail in less than 1000 hours. $P(system operates) = .4096 + .4096 + .1536 = .9728.$

## 3.51

a. P(at least one 6 in four rolls) = 1 – P(no 6’s in four rolls) = 1 – (5/6)4 = 0.51775.
b. Note that in a single toss of two dice, P(double 6) = 1/36. Then:
P(at least one double 6 in twenty–four rolls) = 1 – P(no double 6’s in twenty–four rolls) = 1 – (35/36)24 = 0.4914.

## 3.55

$$
E\{Y(Y-1)(Y-2)\}
= \sum_{y=0}^{n} \frac{y(y-1)(y-2)n!}{y!(n-y)!} p^y (1-p)^{n-y}
= \sum_{y=3}^{n} 
\frac{n(n-1)(n-2)(n-3)!}{(y-3)!(n-3-(y-3))!} p^y (1-p)^{n-y}
$$

$$
= n(n-1)(n-2)p^3 
\sum_{z=0}^{n-3} \binom{n-3}{z} p^z (1-p)^{n-3-z}
= n(n-1)(n-2)p^3
$$

Equating this to $E(Y^3) - 3E(Y^2) + 2E(Y)$, it is found that

$$E(Y^3) = 3n(n-1)p^2 - n(n-1)(n-2)p^3 + np.
$$

## 3.59

If Y = # of defective motors, then Y is binomial with n = 10 and p = .08. Then, $E(Y) = .8$. The seller’s expected next gain is \$1000 – \$200E(Y) = \$840.

# Submitted Problems

## 3.38

Note that $Y$ is binomial with $n = 4$, $p = 1/3 = P(\text{judge chooses formula } B)$.

a. $p(y) = \binom{4}{y}\left(\frac{1}{3}\right)^y \left(\frac{2}{3}\right)^{4-y}, \quad y = 0,1,2,3,4.$

b. $P(Y \ge 3) = p(3) + p(4) = \frac{8}{81} + \frac{1}{81} = \frac{9}{81} = \frac{1}{9}.$

c. $E(Y) = 4\left(\frac{1}{3}\right) = \frac{4}{3}.$

d. $V(Y) = 4\left(\frac{1}{3}\right)\left(\frac{2}{3}\right) = \frac{8}{9}.$

## 3.40

Let $Y =$ number that recover from stomach disease. Then $Y$ is binomial with $n = 20$ and $p = .8$.  
To find these probabilities, Table 1 in Appendix III will be used.

a. $P(Y \ge 10) = 1 - P(Y \le 9) = 1 - .001 = .999.$

b. $P(14 \le Y \le 18) = P(Y \le 18) - P(Y \le 13) = .931 - .087 = .844.$

c. $P(Y \le 16) = .589.$

## 3.44

Let $Y =$ number of successful operations, $Y \sim \text{Binomial}(n=5,p)$

- With $p=0.8$: $P(Y=5) = 0.8^5 = 0.328$
- With $p=0.6$: $P(Y=4) = 5(0.6^4)(0.4) = 0.259$
- With $p=0.3$: $P(Y<2) = P(Y=1)+P(Y=0) = 0.528$

## 3.48

a. Let $Y =$ number of sets that detect the missile. Then $Y$ has a binomial distribution with $n = 5$ and $p = .9$. Then,

$$
P(Y = 4) = 5(.9)^4(.1) = 0.32805
$$

and

$$
P(Y \ge 1) = 1 - P(Y = 0) = 1 - (.1)^5 = 0.99999.
$$

b. With $n$ radar sets, the probability of at least one detection is $1 - (.1)^n$.  

If $1 - (.1)^n = .999$, then $n = 3$.

## 3.50

The only way team A can win in exactly 5 games is to win 3 in the first 4 games and then win the $5^{\text{th}}$ game. Let $Y =$ number of games team A wins in the first 4 games. Thus, $Y$ has a binomial distribution with $n = 4$. Thus, the desired probability is given by

$$
P(\text{Team A wins in 5 games}) = P(Y = 3)P(\text{Team A wins game 5})
$$

$$
= \binom{4}{3} p^3(1-p)p = 4p^4(1-p).
$$

## 3.56

Using expression for the mean and variance of Y = # of successful explorations, a binomial random variable with $n = 10$ and $p = .1$, $E(Y) = 10(.1) = 1$, and $V(Y) = 10(.1)(.9) = 0.9$.

## 3.58

If $Y \sim \text{Binomial}(n=4,p=0.1)$:

$E(Y) = 0.4$, $V(Y) = 0.36$, so $E(Y^2) = 0.36 + (0.4)^2 = 0.52$

Then $E(C) = 3(0.52) + (0.36) + 2 = 3.96$


