---
title: "HW 08 SOLUTIONS"
format: pdf
---

# Practice Problems

## 4.89  
(a) Note that $\int_2^{\infty} \frac{1}{\beta} e^{-y/\beta} dy = e^{-2/\beta}=0.0821 \Rightarrow \beta = 0.8$  
(b) $P(Y \le 1.7) = 1 - e^{-1.7/0.8} = 0.5075$

## 4.93  
Let $Y$ be the time between fatal airplane accidents. So $Y \sim \text{Exponential}(\beta=44)$.  
(a) $P(Y \le 31) = \int_0^{31}\frac{1}{44}e^{-y/44}=1 - e^{-31/44} = 0.5057$  
(b) $V(Y) = \beta^2 = 44^2 = 1936$

## 4.109  
$Y \sim \text{Gamma}(\alpha=3,\ \beta=2)$, $L = 30Y + 2Y^2$  
$E(L) = 30E(Y)+2E(Y^2)=30(6)+2(12+6^2)=276$  
$V(L) = E(L^2)-[E(L)]^2=E(900Y^2 + 120Y^3 + 4Y^4) - 276^2.$
$E(Y^3) = \int+0^{\infty}\frac{y^5}{16}e^{-y/2} = 480$ and $E(Y^4) = \int+0^{\infty}\frac{y^6}{16}e^{-y/2} = 5760$
Thus, $V(Y) = 900(48)+120(480)+4(5760)-276^2=47664$

## 4.123a  
$Y \sim \text{Beta}(\alpha=4,\ \beta=3)$, $k = \frac{\Gamma(4+3)}{\Gamma(4)\Gamma(3)}=60$  
95th percentile: $\phi_{.95} = 0.84684$

## 4.127  
For $\alpha=\beta=1$,  $f(y) = \frac{\Gamma(2)}{\Gamma(1)\Gamma(1)}y^{1-1}(1-y)^{1-1}=1\Rightarrow Y \sim \text{Uniform}(0,1)$

## 4.165  
The pdf of $Y$ is in the form of a gamma density with $Y \sim \text{Gamma}(\alpha=2,\ \beta=0.5)$  
(a) $c = \frac{1}{\Gamma(2)0.5^2}=4$  
(b) $E(Y)=\alpha\beta=2(0.5)=1$, $V(Y)=\alpha\beta^2=2(.5)^2=0.5$  
(c) MGF: $M(t) = (1 - \beta t)^{-\alpha} = (1-0.5t)^{-2},\ t<2$

# Submitted Problems

## 4.96abc
$Y \sim \text{Gamma}(\alpha=4,\ \beta=2)$
(a) $k = 1/(\Gamma(4)2^4) = 1/96$
(b) $Y \sim \chi^2$ with $\nu = 2\alpha = 8$ degrees of freedom
(c) $E(Y) = \alpha\beta = 4(2) = 8$, $V(Y) = \alpha\beta^2 =4(2^2)= 16$

## 4.104
$Y \sim \text{Exponential}(\beta=100)$, $P(Y>200)=e^{-2}$ Let the random variable $X$ be the number of components that operate in the equipment for more than 200 hours. Then
$X \sim \text{Binomial}(n=3, p=e^{-2})$, $P(X\ge2)=P(X=2)+P(X=3)=3(e^{-2})^2(1 - e^{-2}) + (e^{-2})^3=0.05$

## 4.110
$Y \sim \text{Gamma}(\alpha=3,\ \beta=0.5)$, $E(Y)=1.5$, $V(Y)=0.75$

## 4.126
(a) $\int_0^y(6t - 6t^2)dt = 3y^2 - 2y^3$, so
$F(y)=\begin{cases}0,&y<0\\ 3y^2-2y^3,&0\le y\le1\\1,&y>1\end{cases}$

(b) not shown

(c) $P(0.5 \leq Y \leq 0.8) = F(0.8) - F(0.5) = 1.92 - 1.092 - 0.75 + 0.25 = 0.396$

## 4.130
$\sigma^2 = E(Y^2)-\mu^2$,
$$E(Y^2) = \frac{\Gamma(\alpha + \beta)}{\Gamma(\alpha)\Gamma(\beta)}\int_0^1 y^{\alpha + 1}(1 - y)^{\beta-1}dy=\frac{\Gamma(\alpha + \beta)}{\Gamma(\alpha)\Gamma(\beta)}\frac{\Gamma(\alpha + 2)\Gamma(\beta)}{\Gamma(\alpha + 2 + \beta)} = \frac{(\alpha + 1)\alpha}{(\alpha + \beta)(\alpha + \beta + 1)}$$
$V(Y) = \frac{(\alpha + 1)\alpha}{(\alpha + \beta)(\alpha + \beta + 1)} - \left(\frac{\alpha}{\alpha + \beta}\right)^2 = \frac{\alpha\beta}{(\alpha + \beta)^2(\alpha + \beta + 1)}$
