---
title: "Practice Exam 2"
output: pdf_document
---

**1. (20 points)** The daily sales at a local bookstore that focuses on books in mathematics, statistics, and finance are normally distributed with mean \$1200 and standard deviation \$200. You may find the `qnorm()` and/or `pnorm()` output below to be useful in completing this problem.

(a) Find the probability that the daily sales are between \$900 and \$1500.

(b) Find the interval that contains the middle 40% of daily sales numbers.

(c) Daily sales are independent from one day to the next. What is the probability that the daily sales are outside the interval (\$900,\$1500) at least twice in a five-day work week?

| z     | `pnorm(z)` |
|-------|----------|
| -2    | 0.023    |
| -1.5  | 0.067    |
| -1    | 0.159    |
| -0.5  | 0.309    |
| 0.5   | 0.691    |
| 1     | 0.841    |
| 1.5   | 0.933    |
| 2     | 0.977    |

| p     | `qnorm(p)` |
|-------|----------|
| 0.1   | -1.282    |
| 0.2  | -0.842    |
| 0.3    | -0.524    |
| 0.4  | -0.253    |
| 0.6    | 0.253    |
| 0.7   | 0.524    |
| 0.8    | 0.842    |
| 0.9    | 1.282    |


\pagebreak

**2. (10 points)** An urn contains four balls labeled with the integers 1 to 4. Suppose that two balls are selected at random from the urn without replacement. Let $X$ be the smaller of the two integers on the selected balls, and let $Y$ be the larger of the two. For example, if the integers are 4 (first draw) and 1 (second), then $X = 1$ and $Y = 4$. 

(a) Find the joint distribution for $X$ and $Y$.

(a) Find the marginal distribution of $Y$

(a) Find $p(x|y = 3)$

---

**3. (15 points)** The random variable $X$ has probability density function
$$
f(x) =
\begin{cases}
x^2, & -1 < x < 0, \\\\
c x, & 0 < x < 2, \\\\
0, & \text{otherwise}.
\end{cases}
$$

(a) Find the value of $c$ that makes $f(x)$ a valid probability density function.

(b) Find the cumulative distribution function for $X$.

---

**4. (15 points)** The side length $S$ of a square is uniformly distributed on the interval $[2,4]$.

(a) Write down the probability density function for $S$.

(b) Find the expected value for the area $A = S^2$ of the square.

(c) Find the variance for the area $A = S^2$ of the square.

---

**5. (10 points)** Find a formula for $E[X^3]$ when $X$ follows the Gamma$(\alpha,\beta)$ distribution. Put your answer in terms of $\alpha$ and $\beta$, with no instances of the gamma function showing up.

---

**6. (10 points)** The random variable $X$ has moment generating function
$$
m(t) = (0.5 + 0.5 e^{2t})^2.
$$

(a) Find $E[X]$.

(b) Find $V(X)$.

---

**7. (15 points)** The total medical claims each year for employees in a company is modeled with pdf $f(y) = 2(1 - y), \ \ 0 \leq y \leq 1$, where $y$ is in \$100,000s.

(a) Find the mean of the total claims
(b) Find the 90th percentile of the distribution
(c) If the company set aside \$75,000, what is the probability they cover all the claims for a year.

---

**8. (5 points)** A compter randomly generates a number $Y$ that ranges from 100 to 150. Consider the following function:

$$ h(y) =
\begin{cases}
0, & y<100\\
0.02y - 2, & 100 \leq y\leq150\\
0, & y > 150
\end{cases}
$$

The function $h(y)$ is ___________.

A) the cumulative distribution function (cdf) of $Y$
B) the probability density function (pdf) of $Y$
C) neither the cdf nor the pdf of $Y$

Justify your answer.