---
title-block: false
format: pdf
---

**STAT 5700 — Quiz 2**  
**Date:** September 11, 2025  
\textbf{\textcolor{red}{SOLUTIONS}}
\
\

1. (1pt) There are 20 students in this class. For group work, you split into 5 groups of 4 students each. How many group compositions are possible? Write out the formula, you do not need to complete the calculation. 

$$\textcolor{red}{\binom{20}{4 \ 4 \ 4\ 4\ 4} = \frac{20!}{4!4!4!4!4!}}$$

2. (4pts) Let A and B be two events such that $P(A) = 0.4$, $P(B) = 0.3$, and $P(A \cap B) = 0.2$.

    a. Find $P(A | B)$
    b. Find $P(A | A \cup B)$
    c. Find $P(A | A \cap B)$
    d. Are A and B independent? Justify your answer. 



\textbf{\textcolor{red}{Part a solution}}

$P(A \mid B) = \frac{P(A \cap B)}{P(B)} = \frac{0.2}{0.3} = \tfrac{2}{3}$

\textbf{\textcolor{red}{Part b solution}}

$P(A \mid A \cup B) = \frac{P(A \cap (A \cup B))}{P(A \cup B)} =\frac{P(A)}{P(A \cup B)}$

$P(A \cup B) = P(A) + P(B) - P(A \cap B) = 0.4 + 0.3 - 0.2 = 0.5$

Therfore: $P(A \mid A \cup B) = \frac{0.4}{0.5} = 0.8$

\textbf{\textcolor{red}{Part c solution}}

$P(A \mid A \cap B) = \frac{P(A \cap (A \cap B))}{P(A \cap B)} = \frac{P(A \cap B)}{P(A \cap B)} = 1$

\textbf{\textcolor{red}{Part d solution}}

Two events are independent if  and only if $P(A \cap B) = P(A) \cdot P(B).$

Here $P(A) \cdot P(B) = (0.4)(0.3) = 0.12$, but
$P(A \cap B) = 0.2$, so the events **are not independent**.