---
title-block: false
header-includes:
  - \pagestyle{empty}
  - \pagenumbering{gobble}
format:
  pdf:
    fontsize: 10pt
---

**STAT 5700 — Quiz 9 SOLUTIONS**  
**Date:** December 4, 2025  

**(2pts) Problem 1** Let $X$ and $Y$ be two independent, continuous random variables with pdfs $f_X(x) = 2x, \ \  0 < x < 1$, and $f_Y(y) = 3y^2, \ \ 0 < y < 1$. Find the following:

a. $P(X < Y)$
b. $\rho_{XY}$

### SOLUTION part a

Because $X$ and $Y$ are independent, $\rho_{XY} = 0$

### SOLUTION part b

Due to independence, the covariance is 0, which means the correlation is 0.

**(2pts) Problem 2** Let $\mu_X = 2$, $\sigma^2_X = 9$, $\mu_Y = 1$, $\sigma^2_Y = 16$, and $\sigma_{XY} = 3$. Find the following:

a. $V(2X + 4Y)$
b. $Cov(X, 2Y)$
c. $Corr(X, 2Y)$

### SOLUTION part a

$$
V(2X + 4Y) 
= 2^2\sigma_X^2 + 4^2\sigma_Y^2 + 2(2)(4)\sigma_{XY}
= 4\cdot 9 + 16\cdot 16 + 16\cdot 3
= 36 + 256 + 48
= 340.
$$

### SOLUTION part b

$$
\text{Cov}(X, 2Y) = E(X2Y) - E(X)E(2Y) = 2[E(XY) - E(X)E(Y)] = 2Cov(X,Y) = 2(3) = 6.
$$

### SOLUTION part c

 
$$
\text{Corr}(X,2Y) 
= \frac{\text{Cov}(X,2Y)}{\sqrt{V(X)} \sqrt{V(2Y)}}
= \frac{6}{(3)(2)(4)}
= \frac{1}{4}.
$$

**MULTIPLE CHOICE (0.5 each)**

3. Consider two continuous random variables $X$ and $Y$. Which of the following can be negative? Select all that apply. 

    A) $\textcolor{red}{\mu_X}$
    B) $\sigma_X$
    C) $\textcolor{red}{Cov(X,Y)}$
    D) $\textcolor{red}{\rho_{XY}}$

4. The correlation between $W$ and $Z$ is calculated to be exactly 1. $Z$ is plotted against $W$. A line is drawn through all of the data points. The slope of the line _____ equal to 0.5. The slope of the line ____ equal to -2.

    A) could be, could be
    
    **B) could be, could NOT be**
    
    C) could NOT be, could be
   
    D) could NOT be, could NOT be

