---
title-block: false
format: pdf
---

**STAT 5700 — Quiz 1**  
**Date:** September 4, 2025  
\textbf{\textcolor{red}{SOLUTIONS}}

\
\

1. TRUE/FALSE: $P(A \cap B) \leq P(A \cup B)$
\
    \textcolor{red}{TRUE}

2. How many ways are there to choose 3 applicants from a pool of 13 applicants? Write out the formula, but you do not need to calculate the result. 

$$\textcolor{red}{\binom{13}{3} = \frac{13!}{10!3!}}$$


**Use the following scenario to answer Problems 3 - 5**. 

Suppose you toss two fair 6-sided dice. The following events are defined:

+ A: The number on the first die is even

+ B: The number on the first die is odd

+ C: There is an odd number on at least one die


3. Which of the following pairs of events are **mutually exclusive**?
    a. \textcolor{red}{A and B}
    b. A and C
    c. B and C
    d. (a) and (b) are both correct
    e. None of the above

4. Which of the following pairs of events are **mutually exhaustive**?
    a. A and B
    b. A and C
    c. B and C
    d. \textcolor{red}{(a) and (b) are both correct}
    d. None of the above

5. What is $P(A' \cap B')$?

    \textcolor{red}{$P(A' \cap B') = 0$. To see this, note that $A' \cap B' = \emptyset$, or alternatively $A \cup B = 1$, \\ so by DeMorgan's Laws and Rule of Complements, $P(A' \cap B') = P[(A \cup B)'] = 1 - P(A \cup B) = 1 - 1 = 0$}

