---
title-block: false
format: pdf
---

**STAT 5700 — Quiz 7**  
**Date:** November 6, 2025  

**SOLUTIONS**
\
\
**Problem 1 (2pts)** 

The weekly fuel consumption $Y$ (in gallons) for a company’s delivery truck has approximately a gamma distribution with shape parameter $\alpha = 4$ and scale parameter $\beta = 5$. The total weekly fuel cost $C$ (in dollars) is given by  $C = 10Y + 0.5Y^2.$  Find the **expected value** of $C$.

#### SOLUTION

$E(C) = E(10Y + 0.5Y^2) = 10E(Y) + 0.5E(Y^2)$

$E(Y) = \alpha\beta = 4*5 = 20$

$V(Y) = \alpha\beta^2 = 4*5^2 = 100$

$V(Y) = E(Y^2) - [E(Y)]^2 \implies E(Y^2) = V(Y) + [E(Y)]^2 = 100 + 20^2 = 500$

$E(C) = 10(20) + 0.5(500) = 450$


**Problem 2 (2pts)**
The random variable $Y$ represents the proportion of time in a day that a machine is operating without failure. Past data suggest that $Y$ follows a distribution with probability density function  
$$
f(y) = 12y(1 - y)^2, \quad 0 < y < 1
$$  

(a) Identify the name of the distribution for this random variable, and the values of its parameter(s).

$$Beta(\alpha = 2, \beta = 3)$$

(b) Find the **mean** and **variance** of $Y$.

$$E(Y) = \frac{\alpha}{\alpha + \beta} = \frac{2}{5}$$
$$V(Y) = \frac{\alpha\beta}{(\alpha + \beta)^2(\alpha + \beta + 1)} = \frac{6}{5^2(6)} = \frac{1}{25}$$

**Problem 3 (1pt)** Fill in the blanks:

+ The $\textcolor{red}{EXPONENTIAL}$ distribution is a special case of the gamma distribution with $\alpha = 1$. 

+ The $\textcolor{red}{UNIFORM}$ distribution is a special case of the beta distribution with $\alpha = 1$ and $\beta = 1$. 

