---
title-block: false
format: pdf
---

**STAT 5700 — Quiz 5**  
**Date:** October 23, 2025  

**Name:** \underline{\hspace{5cm}}
\
\

**Problem 1 (3pts)** Let $m(t) = \frac{1}{4}e^{t} + \frac{1}{4}e^{3t} + \frac{1}{2}e^{5t}$. Find the following:

+ $E(Y)$
+ $V(Y)$
+ The probability distribution of $Y$

### Solution

$$
m'(t) = \frac{d}{dt} \left( \frac{1}{4}e^t + \frac{1}{4}e^{3t} + \frac{1}{2}e^{5t} \right)
= \frac{1}{4} e^t + \frac{3}{4} e^{3t} + \frac{5}{2} e^{5t}.
$$

$$
E(Y) = m'(0) = \frac{1}{4}(1) + \frac{1}{4}(3) + \frac{1}{2}(5) = \frac{1 + 3 + 10}{4} = \frac{14}{4} = 3.5
$$

$$
m''(t) = \frac{d}{dt} \left( \frac{1}{4} e^t + \frac{3}{4} e^{3t} + \frac{5}{2} e^{5t} \right)
= \frac{1}{4} e^t + \frac{9}{4} e^{3t} + \frac{25}{2} e^{5t}.
$$

$$
E(Y^2) = m''(0) = \frac{1}{4}(1^2) + \frac{1}{4}(3^2) + \frac{1}{2}(5^2) = \frac{1 + 9 + 50}{4} = \frac{60}{4} = 15
$$

$$
V(Y) = E(Y^2) - [E(Y)]^2 = 15 - (3.5)^2 = 15 - 12.25 = 2.75
$$
From the MGF, the probabilities correspond to the coefficients of $e^{yt}$:

| $Y$ | $1$ | $3$ | $5$ |
|-----|-----|-----|-----|
| $P(Y=y)$ | $\frac{1}{4}$ | $\frac{1}{4}$ | $\frac{1}{2}$ |

\pagebreak

**Problem 2 (1pt)** Find an expression for the 100th moment of the Bernoulli distribution (support $y = 0,1$). You answer should be a function of $p$ only. 

### Solution

$p(y) = p^y(1-p)^{1 - y}$ for $y = 0,1$ 

The $n$-th moment is:

$$
E(Y^n) = \sum_{y = 0}^1y^n p^y(1-p)^{1 - y}= 0^np^0(1-p)^1 + 1^np^1(1 - p)^0 = p
$$

So the **100th moment** is:

$$
E(Y^{100}) = p
$$


**TRUE/FALSE (0.5pt each)**

3. FALSE The first central moment, $E(Y - \mu)$, is equal to $\sigma^2$ for all random variables $Y$, where $\mu$ is the mean of $Y$ and $\sigma^2$ is the variance.
4. TRUE If two random variables have the same moment-generating function for all real values of $t$ then they must have the same probability distribution.


